# Generated by Django 6.0.4 on 2026-04-30 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bank_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersession",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="usersession",
            name="country_code",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="usersession",
            name="country_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="usersession",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usersession",
            name="region",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
