# Generated by Django 6.0.4 on 2026-04-27 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EMICalculation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_session_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("loan_amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("interest_rate", models.DecimalField(decimal_places=2, max_digits=5)),
                ("tenure_months", models.IntegerField()),
                (
                    "calculation_method",
                    models.CharField(default="Reducing Balance", max_length=50),
                ),
                (
                    "processing_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("calculation_results", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FDComparison",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_session_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "deposit_amount",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("tenure_preference_months", models.IntegerField()),
                (
                    "min_rate_required",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("comparison_results", models.JSONField(blank=True, null=True)),
                (
                    "selected_bank",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BankFDRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bank_name", models.CharField(max_length=200)),
                ("rate", models.DecimalField(decimal_places=2, max_digits=5)),
                ("min_deposit", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "max_deposit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("tenure_months", models.IntegerField()),
                ("tenure_type", models.CharField(default="FIXED", max_length=20)),
                (
                    "senior_citizen_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("premature_withdrawal", models.BooleanField(default=True)),
                ("loan_against_fd", models.BooleanField(default=True)),
                ("effective_from", models.DateField()),
                ("effective_until", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("source", models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                "ordering": ["-rate", "bank_name"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "tenure_months"],
                        name="bank_app_ba_is_acti_c9ad30_idx",
                    ),
                    models.Index(
                        fields=["bank_name", "is_active"],
                        name="bank_app_ba_bank_na_865a17_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="LoanApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "application_id",
                    models.CharField(editable=False, max_length=50, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("KYC_PENDING", "KYC Pending"),
                            ("COMPLIANCE_CHECK", "Compliance Check"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("DISBURSED", "Disbursed"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        choices=[("IN", "India"), ("US", "United States")],
                        default="IN",
                        max_length=2,
                    ),
                ),
                ("applicant_name", models.CharField(max_length=200)),
                (
                    "applicant_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "applicant_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("pan_number", models.CharField(blank=True, max_length=20, null=True)),
                ("ssn_last_4", models.CharField(blank=True, max_length=4, null=True)),
                (
                    "applicant_income",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "coapplicant_income",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "employment_status",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("employment_years", models.IntegerField(default=0)),
                ("loan_amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("loan_term_months", models.IntegerField(default=0)),
                (
                    "loan_purpose",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("credit_score", models.IntegerField(blank=True, null=True)),
                (
                    "dti_ratio",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "existing_loans",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "collateral_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "collateral_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("risk_assessment", models.JSONField(blank=True, null=True)),
                (
                    "approval_probability",
                    models.DecimalField(decimal_places=4, default=0, max_digits=5),
                ),
                ("risk_grade", models.CharField(blank=True, max_length=10, null=True)),
                ("kyc_status", models.CharField(default="PENDING", max_length=20)),
                ("kyc_data", models.JSONField(blank=True, null=True)),
                (
                    "compliance_status",
                    models.CharField(default="PENDING", max_length=20),
                ),
                ("compliance_results", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["application_id"], name="bank_app_lo_applica_1a7811_idx"
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="bank_app_lo_status_dd7045_idx",
                    ),
                    models.Index(
                        fields=["region", "status"],
                        name="bank_app_lo_region_4a1306_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="KYCDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("AADHAAR", "Aadhaar Card"),
                            ("PAN", "PAN Card"),
                            ("PASSPORT", "Passport"),
                            ("VOTER_ID", "Voter ID"),
                            ("DRIVING_LICENSE", "Driving License"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("document_number", models.CharField(max_length=100)),
                ("file_path", models.CharField(max_length=500)),
                ("file_size", models.IntegerField(default=0)),
                ("extracted_data", models.JSONField(blank=True, null=True)),
                (
                    "extraction_confidence",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "verification_status",
                    models.CharField(default="PENDING", max_length=20),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kyc_documents",
                        to="bank_app.loanapplication",
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="ComplianceScreening",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entity_name", models.CharField(max_length=200)),
                ("entity_type", models.CharField(default="PERSON", max_length=50)),
                ("search_query", models.JSONField()),
                ("yente_results", models.JSONField(blank=True, null=True)),
                ("wikidata_results", models.JSONField(blank=True, null=True)),
                ("is_sanctioned", models.BooleanField(default=False)),
                ("is_pep", models.BooleanField(default=False)),
                (
                    "risk_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("risk_level", models.CharField(blank=True, max_length=20, null=True)),
                ("sanctions_flags", models.JSONField(blank=True, default=list)),
                ("pep_flags", models.JSONField(blank=True, default=list)),
                (
                    "screening_status",
                    models.CharField(default="COMPLETED", max_length=20),
                ),
                ("screened_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compliance_screenings",
                        to="bank_app.loanapplication",
                    ),
                ),
            ],
            options={
                "ordering": ["-screened_at"],
            },
        ),
        migrations.CreateModel(
            name="UserSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(max_length=100, unique=True)),
                ("user_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("session_data", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_activity", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-last_activity"],
                "indexes": [
                    models.Index(
                        fields=["session_id", "is_active"],
                        name="bank_app_us_session_0cca1d_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("LOAN_SUBMITTED", "Loan Submitted"),
                            ("LOAN_APPROVED", "Loan Approved"),
                            ("LOAN_REJECTED", "Loan Rejected"),
                            ("KYC_UPLOADED", "KYC Uploaded"),
                            ("KYC_VERIFIED", "KYC Verified"),
                            ("COMPLIANCE_CHECKED", "Compliance Checked"),
                            ("EMI_CALCULATED", "EMI Calculated"),
                            ("FD_COMPARED", "FD Compared"),
                        ],
                        max_length=50,
                    ),
                ),
                ("actor_type", models.CharField(default="SYSTEM", max_length=50)),
                ("actor_id", models.CharField(blank=True, max_length=100, null=True)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="bank_app.loanapplication",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["application", "created_at"],
                        name="bank_app_au_applica_d58c64_idx",
                    ),
                    models.Index(
                        fields=["action", "created_at"],
                        name="bank_app_au_action_d4813c_idx",
                    ),
                ],
            },
        ),
    ]
