# Generated by Django 6.0.4 on 2026-04-30 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bank_app", "0002_usersession_city_usersession_country_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("LOAN_SUBMITTED", "Loan Submitted"),
                    ("LOAN_APPROVED", "Loan Approved"),
                    ("LOAN_REJECTED", "Loan Rejected"),
                    ("KYC_UPLOADED", "KYC Uploaded"),
                    ("KYC_VERIFIED", "KYC Verified"),
                    ("COMPLIANCE_CHECKED", "Compliance Checked"),
                    ("EMI_CALCULATED", "EMI Calculated"),
                    ("FD_COMPARED", "FD Compared"),
                    ("CREWAI_AUTO_APPROVED", "CrewAI Auto Approved"),
                    ("CREWAI_AUTO_REJECTED", "CrewAI Auto Rejected"),
                    ("CREWAI_REQUIRES_REVIEW", "CrewAI Requires Human Review"),
                    ("KYC_UPDATED", "KYC Status Updated"),
                    ("COMPLIANCE_UPDATED", "Compliance Status Updated"),
                    ("LOAN_UPDATED", "Loan Updated"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="CrewAIReasoningLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("crew_type", models.CharField(max_length=50)),
                ("decision", models.CharField(max_length=20)),
                (
                    "confidence_score",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("reasoning", models.JSONField()),
                ("factors", models.JSONField(default=list)),
                ("recommendations", models.JSONField(default=list)),
                ("executed_at", models.DateTimeField(auto_now_add=True)),
                ("auto_executed", models.BooleanField(default=False)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crewai_reasoning_logs",
                        to="bank_app.loanapplication",
                    ),
                ),
            ],
            options={
                "ordering": ["-executed_at"],
            },
        ),
    ]
