# Generated by Django 6.0.4 on 2026-05-04 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0006_add_database_query_log'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='fixeddeposit',
            name='bank_app_fi_status_...',
        ),
        migrations.RenameIndex(
            model_name='databasequerylog',
            new_name='bank_app_da_status_bd997b_idx',
            old_name='bank_app_da_status_exec_idx',
        ),
        migrations.RenameIndex(
            model_name='databasequerylog',
            new_name='bank_app_da_execute_9beba3_idx',
            old_name='bank_app_da_execute_exec_idx',
        ),
        migrations.RenameIndex(
            model_name='databasequerylog',
            new_name='bank_app_da_is_read_3e0417_idx',
            old_name='bank_app_da_is_read_exec_idx',
        ),
        migrations.RenameIndex(
            model_name='emailcampaign',
            new_name='bank_app_em_status_fd759e_idx',
            old_name='bank_app_em_status_8f8a0e_idx',
        ),
        migrations.RenameIndex(
            model_name='emailcampaign',
            new_name='bank_app_em_templat_265ee8_idx',
            old_name='bank_app_em_template_2c5d1a_idx',
        ),
        migrations.RenameIndex(
            model_name='emailcampaignlog',
            new_name='bank_app_em_campaig_6d61b8_idx',
            old_name='bank_app_em_campaign_4e7b2c_idx',
        ),
        migrations.RenameIndex(
            model_name='emailcampaignlog',
            new_name='bank_app_em_recipie_a0fca0_idx',
            old_name='bank_app_em_recipie_8a3f1d_idx',
        ),
        migrations.RenameIndex(
            model_name='emailcampaignlog',
            new_name='bank_app_em_trackin_803df4_idx',
            old_name='bank_app_em_tracki_9b4e2f_idx',
        ),
        migrations.RenameIndex(
            model_name='fixeddeposit',
            new_name='fixed_depos_fd_id_944899_idx',
            old_name='bank_app_fi_fd_id_...',
        ),
        migrations.RenameIndex(
            model_name='fixeddeposit',
            new_name='fixed_depos_custome_1c9168_idx',
            old_name='bank_app_fi_custome_...',
        ),
        migrations.AddField(
            model_name='fixeddeposit',
            name='compounding_freq',
            field=models.CharField(db_column='compounding_freq', default='quarterly', max_length=20),
        ),
        migrations.AddField(
            model_name='fixeddeposit',
            name='monthly_installment',
            field=models.DecimalField(blank=True, db_column='monthly_installment', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='fixeddeposit',
            name='premature_penalty_percent',
            field=models.DecimalField(db_column='premature_penalty_percent', decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='fixeddeposit',
            name='product_type',
            field=models.CharField(db_column='product_type', default='FD', max_length=10),
        ),
        migrations.AddField(
            model_name='fixeddeposit',
            name='risk_score',
            field=models.IntegerField(blank=True, db_column='risk_score', null=True),
        ),
        migrations.AddField(
            model_name='fixeddeposit',
            name='user_id',
            field=models.IntegerField(blank=True, db_column='user_id', null=True),
        ),
        migrations.AlterField(
            model_name='fixeddeposit',
            name='account_number',
            field=models.CharField(blank=True, db_column='account_number', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fixeddeposit',
            name='amount',
            field=models.DecimalField(db_column='initial_amount', decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='fixeddeposit',
            name='auto_renewal',
            field=models.BooleanField(db_column='auto_renewal', default=False),
        ),
        migrations.AlterField(
            model_name='fixeddeposit',
            name='bank_name',
            field=models.CharField(db_column='bank_name', max_length=200),
        ),
        migrations.AlterField(
            model_name='fixeddeposit',
            name='certificate_generated',
            field=models.BooleanField(db_column='certificate_generated', default=False),
        ),
        migrations.AlterField(
            model_name='fixeddeposit',
            name='certificate_path',
            field=models.CharField(blank=True, db_column='certificate_path', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='fixeddeposit',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, db_column='confirmed_at', null=True),
        ),
        migrations.AlterField(
            model_name='fixeddeposit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='created_at'),
        ),
        migrations.AlterField(
            model_name='fixeddeposit',
            name='customer_email',
            field=models.EmailField(blank=True, db_column='customer_email', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='fixeddeposit',
            name='customer_name',
            field=models.CharField(blank=True, db_column='customer_name', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fixeddeposit',
            name='customer_phone',
            field=models.CharField(blank=True, db_column='customer_phone', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fixeddeposit',
            name='email_sent',
            field=models.BooleanField(db_column='email_sent', default=False),
        ),
        migrations.AlterField(
            model_name='fixeddeposit',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, db_column='email_sent_at', null=True),
        ),
        migrations.AlterField(
            model_name='fixeddeposit',
            name='fd_id',
            field=models.AutoField(db_column='fd_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fixeddeposit',
            name='interest_earned',
            field=models.DecimalField(db_column='interest_earned', decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='fixeddeposit',
            name='loan_against_fd',
            field=models.BooleanField(db_column='loan_against_fd', default=False),
        ),
        migrations.AlterField(
            model_name='fixeddeposit',
            name='maturity_amount',
            field=models.DecimalField(db_column='maturity_amount', decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='fixeddeposit',
            name='maturity_date',
            field=models.DateField(blank=True, db_column='maturity_date', null=True),
        ),
        migrations.AlterField(
            model_name='fixeddeposit',
            name='rate',
            field=models.DecimalField(db_column='interest_rate', decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='fixeddeposit',
            name='region',
            field=models.CharField(choices=[('IN', 'India'), ('US', 'United States')], db_column='region', default='IN', max_length=2),
        ),
        migrations.AlterField(
            model_name='fixeddeposit',
            name='senior_citizen',
            field=models.BooleanField(db_column='senior_citizen', default=False),
        ),
        migrations.AlterField(
            model_name='fixeddeposit',
            name='start_date',
            field=models.DateField(db_column='start_date'),
        ),
        migrations.AlterField(
            model_name='fixeddeposit',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('MATURED', 'Matured'), ('CLOSED', 'Closed'), ('PREMATURELY_CLOSED', 'Prematurely Closed')], db_column='fd_status', default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='fixeddeposit',
            name='tenure_months',
            field=models.IntegerField(db_column='tenure_months'),
        ),
        migrations.AlterField(
            model_name='fixeddeposit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='updated_at'),
        ),
        migrations.AlterField(
            model_name='fixeddeposit',
            name='user_session_id',
            field=models.CharField(blank=True, db_column='user_session_id', max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='fixeddeposit',
            index=models.Index(fields=['status'], name='fixed_depos_fd_stat_287a6f_idx'),
        ),
        migrations.AlterModelTable(
            name='fixeddeposit',
            table='fixed_deposit',
        ),
        migrations.RemoveField(
            model_name='fixeddeposit',
            name='id',
        ),
    ]
